### ISSUE TITLE
java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader

### ISSUE THREAD

**Issue by davidjstudholme** [fredeBio/REALPHY#1]
```$ java -jar -Xmx20000m RealPhy_v112.jar input_fasta_only output_fasta_only -config config.txt -treeBuilder 2```

Gives the following error. Any ideas please?

```Preparing reference...
input_fasta_only/GCA_000260195.2_FO_II5_V1_genomic.fna output_fasta_only/GCA_000260195.2_FO_II5_V1_genomic/core/GCA_000260195.2_FO_II5_V1_genomic.fas
Cut fasta sequence files into fragments...
input_fasta_only/cut/GCA_000260195.2_FO_II5_V1_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_000350345.1_Foc1_1.0_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_000350365.1_Foc4_1.0_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_001696625.1_C1HIR_9889_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_005930515.1_ASM593051v1_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_007994515.1_ASM799451v1_genomic_50fasta.fastq.gz already exists. Continue with next file.
input_fasta_only/cut/GCA_011316005.1_ASM1131600v1_genomic_50fasta.fastq.gz already exists. Continue with next file.
Running alignment program to align sequence fragments to reference...
Determine SNPs...
Strain  #mapped nucleotides/total possible|Number of polymorphic sites present in all strains analysed to that point

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader
        at solexa.PointSubstitutionsBAM.read(PointSubstitutionsBAM.java:172)
        at solexa.PointSubstitutions.<init>(PointSubstitutions.java:39)
        at solexa.PointSubstitutionsBAM.<init>(PointSubstitutionsBAM.java:165)
        at solexa.PointSubstitutionsBAM.<init>(PointSubstitutionsBAM.java:168)
        at buildTreesFromSequenceData.GetPolymorphismsClass.calculatePolymorphisms(GetPolymorphismsClass.java:197)
        at buildTreesFromSequenceData.GetPolymorphismsClass.<init>(GetPolymorphismsClass.java:135)
        at buildTreesFromSequenceData.GetPolymorphismWithGaps.<init>(GetPolymorphismWithGaps.java:30)
        at buildTreesFromSequenceData.RealPhy.getPolymorphisms(RealPhy.java:675)
        at buildTreesFromSequenceData.RealPhy.runAnalyses(RealPhy.java:299)
        at buildTreesFromSequenceData.RealPhy.main(RealPhy.java:77)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.sf.samtools.SAMFileReader
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 15 more```

Many thanks,

David

**Comment by fredeBio** [comment]
I think this problem should be solved with the latest update of the jar file here: https://realphy.unibas.ch/downloads/REALPHY_v113_exec.zip

**Comment by davidjstudholme** [comment]
Thank you very much indeed, Frederic. This does indeed solve this problem and I think we can now close this issue.

**Comment by Elenombi** [comment]
Hi Frederic,

just FYI, with conda https://anaconda.org/bioconda/realphy there is still the v11.2 version, when I tried I run into the same problem as above (solved by downloading the new version).

Cheers

**Comment by fredeBio** [comment]
Hello,
REALPHY would just need to be compiled with a current java version. Or linked to the new version (https://realphy.unibas.ch/downloads/REALPHY_v113_exec.zip).

Trying to solve it now.

**Comment by CFGrote** [comment]
See this PR to bioconda/recipes: https://github.com/bioconda/bioconda-recipes/pull/27095
