### ISSUE TITLE
Broken link http://realphy.unibas.ch/fcgi/realphy

### ISSUE THREAD

**Issue by davidjstudholme** [fredeBio/REALPHY#2]
On your Readme.md you have a link to http://realphy.unibas.ch/fcgi/realphy but this URL just gives a 404 File not Found error.

Cheers,

David

**Comment by fredeBio** [comment]
Sorry David. That’s a java version problem. It should work with the version here: https://realphy.unibas.ch/downloads/REALPHY_v112_exec.zip
----- Original Message -----

**Comment by davidjstudholme** [comment]
Thank you for the prompt response, fredeBio.

Unfortunately, using this version, I get exactly the same message:


djs217@bio-training-server:/mnt/bio-surimi-data/fusarium/realphy$ java -jar -Xmx20000m RealPhy_v112.jar input_fasta_only output_fasta_only -config config.txt -treeBuilder 2

Preparing reference...

Determine SNPs...

Strain  #mapped nucleotides/total possible|Number of polymorphic sites present in all strains analysed to that point



Exception in thread "main" java.lang.reflect.InvocationTargetException

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

Caused by: java.lang.NoClassDefFoundError: net/sf/samtools/SAMFileReader

        at solexa.PointSubstitutionsBAM.read(PointSubstitutionsBAM.java:172)

        at solexa.PointSubstitutions.<init>(PointSubstitutions.java:39)

        at solexa.PointSubstitutionsBAM.<init>(PointSubstitutionsBAM.java:165)

        at solexa.PointSubstitutionsBAM.<init>(PointSubstitutionsBAM.java:168)

        at buildTreesFromSequenceData.GetPolymorphismsClass.calculatePolymorphisms(GetPolymorphismsClass.java:197)

        at buildTreesFromSequenceData.GetPolymorphismsClass.<init>(GetPolymorphismsClass.java:135)

        at buildTreesFromSequenceData.GetPolymorphismWithGaps.<init>(GetPolymorphismWithGaps.java:30)

        at buildTreesFromSequenceData.RealPhy.getPolymorphisms(RealPhy.java:675)

        at buildTreesFromSequenceData.RealPhy.runAnalyses(RealPhy.java:299)

        at buildTreesFromSequenceData.RealPhy.main(RealPhy.java:77)

        ... 5 more

Caused by: java.lang.ClassNotFoundException: net.sf.samtools.SAMFileReader

        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

        ... 15 more


You say it is a Java version issue. Is there Java version that you can recommend? if so I will try running using that different Java version.

Best wishes,

David

**Comment by fredeBio** [comment]
Hey David,
sorry again. 

You could compile the source code with your java version. But before you do that, you can try the attached version.

Cheers,
Frederic

----- Original Message -----

**Comment by davidjstudholme** [comment]
Thanks, Frederic.

This mail is, I think, in the wrong thread. This thread is about the broken link on your GitHub page: https://github.com/fredeBio/REALPHY/issues/2

But your message concerns the java problem here: https://github.com/fredeBio/REALPHY/issues/1

Thanks and best wishes,

David

**Comment by fredeBio** [comment]
Changed the link. So it should work now.

**Comment by davidjstudholme** [comment]
Thanks, Frederic. Yes, the link works fine now.
