### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by lukaskon** [fredeBio/REALPHY#5]
Hello, I am new to this and unsure if the error below is a java compatibility issue (tried multiple versions) or something else. Any idea?
Thanks in advance.

```
java -Xmx3000m -jar RealPhy/RealPhy_v113.jar WG_Phylogeny WG_Phylogeny/output -quality 30 -ref B.cinerea_B05.10 -genes -config WG_Phylogeny/output/config.txt
```

```
Preparing reference...
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.remove(ArrayList.java:535)
        at buildTreesFromSequenceData.DetermineCoreGenome.chooseGenomes(DetermineCoreGenome.java:137)
        at buildTreesFromSequenceData.DetermineCoreGenome.runDetermineCoreGenome(DetermineCoreGenome.java:44)
        at buildTreesFromSequenceData.RealPhy.determineCore(RealPhy.java:615)
        at buildTreesFromSequenceData.RealPhy.runAnalyses(RealPhy.java:288)
        at buildTreesFromSequenceData.RealPhy.main(RealPhy.java:77)
        ... 5 more

```

```
Currently Loaded Modules:
  1) MATLAB/2018a    11) OpenMPI/1.10.3-CUDA
  2) powertools/1.2  12) zlib/1.2.12
  3) Boost/1.67.0    13) OpenBLAS/0.2.18-LAPACK-3.6.1
  4) GMP/6.1.2       14) FFTW/3.3.4
  5) GCCcore/5.4.0   15) ScaLAPACK/2.0.2-OpenBLAS-0.2.18-LAPACK-3.6.1
  6) binutils/2.26   16) libffi/3.2.1
  7) GNU/5.4.0-2.26  17) ncurses/6.3
  8) numactl/2.0.11  18) FASTX-Toolkit/0.0.14
  9) hwloc/1.11.3    19) Java/JDK12
 10) CUDA/9.2.88

Inactive Modules:
  1) bzip2/1.0.8   4) cURL/7.83.0       7) imkl/2018.1.163   10) Tcl/8.6.8
  2) XZ/5.2.5      5) SAMtools/1.16.1   8) CMake/3.11.1      11) SQLite/3.21.0
  3) OpenSSL/1.1   6) tbb/2018_U3       9) libreadline/7.0   12) Python/3.6.4

```

config.txt file
```
BOWTIE2 /opt/software/Bowtie2/2.4.2-GCC-10.2.0
BOWTIE2BUILDER /opt/software/Bowtie2/2.4.2-GCC-10.2.0/bin/bowtie2-build
RAXML /opt/software/RAxML/8.2.12-intel-2019a-hybrid-avx2
Rscript /opt/software/R/4.2.2-foss-2021b/bin/Rscript
PhyML /opt/software/PhyML/3.3.20190321-foss-2018b
```

**Comment by mpachkov** [comment]
Hi @lukaskon !

I suspect that there is a problem with your input data.
I suggest that you upload your data to https://realphy.unibas.ch so I can validate the input data see how realphy is executed in our environment.

Best,

Mikhail

**Comment by lukaskon** [comment]
Hi Mikhail, thanks for the quick response. 

I think there could be 3 possible explanations here, hopefully easily fixed!

1) You are correct and there is a problem with my input data. I am inputting paired fastq files that have undergone very little processing (just some filtering for quality and trimming). I wanted to try this out with just a couple to start. Are there more specific guidelines that I missed? If not, I'll be happy to share the data.

2) I asked someone who works with our HPC system and they said there appears to be a bug in the source code "they are trying to the length of null instead of a list, which causes the NullPointerException". 

3) A few of my executables were pointed to the directory instead of the actual executable. I'll fix this, but I am not sure its the issue.

Thanks in advance! Let me know if I can provide other helpful info.

**Comment by mpachkov** [comment]
Hi!

I am sure that the problem is in the reference. I strongly suggest that you upload your data to the Realphy server so I can test it. I do not think that it has anything to do with paths to programs.

Best,

Mikhail

**Comment by mpachkov** [comment]
Hi!

Have you uploaded the data to the server (realphy.unibas.ch)?

Best,

Mikhail

**Comment by lukaskon** [comment]
Trying it out currently! For PE reads, how are the R1 and R2 fastq files supposed to be uploaded? Maybe I've missed this in the manual. Thank you.

**Comment by mpachkov** [comment]
Paired end fastq files should and end with "_R1.fastq.gz" and "_R2.fastq.gz".

Best,

Mikhail

**Comment by mpachkov** [comment]
I have found and checked your submission to the server.
The problem I see is that your B.cinerea_B05.10.gb does not contain any gene information and DNA sequence.

Best,

Mikhail

**Comment by decodecure-tech** [comment]
Hello, I faced the same error, I used the same version as Manual PDF, I'd like to know how I can resolve this or any idea?
Thanks

**Comment by ismara-unibas** [comment]
Hi!

If you are facing the same error then the same solution should work. Check your reference genbank file and make sure that it contains nucleotide sequence and gene annotation.

Otherwise upload you dataset to the realphy server, I will check what causing the error.

Best,

Mikhail

**Comment by decodecure-tech** [comment]
Hi Mikhail, thanks for your reply.

We've uploaded the data(fasta files) several days ago via the email:  hung.kwokwang@decodecure.com, it's running now, and this is the check link: https://realphy.unibas.ch/REALPHY/scratch/data_ct6kxhz8/report/
Thank you.

Best,
Yiqi

**Comment by ismara-unibas** [comment]
Dear Yiqi,

Your job is finished without any problem. If you have not received automatic email from the server, then you access results with this link:
`https://realphy.unibas.ch/REALPHY/scratch/data_ct6kxhz8/report/`

Best,

Mikhail
